### ISSUE TITLE
makeGlobalSet panic

### ISSUE THREAD

**Issue by bws0013** [bws0013/WebScrapperGo#1]
Figure out why this happens (10/8/16):

panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xb code=0x1 addr=0x0 pc=0x32f4]

```
goroutine 1 [running]:
panic(0x326680, 0xc82000a0d0)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
main.getPageWords(0xc8201421e0, 0x10, 0x1)
    /Users/bensmith/GitHub/WebScrapperGo/web.go:89 +0x5b4
main.makeGlobalSet(0x3e7020, 0x1b, 0x1)
    /Users/bensmith/GitHub/WebScrapperGo/web.go:68 +0x368
main.main()
    /Users/bensmith/GitHub/WebScrapperGo/web.go:36 +0x148
```

**Comment by bws0013** [comment]
The solution was to check if there was an error here:
response, err := http.Get(url)
if so, don't try to parse the page. 
Also I make sure every page starts with http:// or https:// before they are looked at. This may have also been causing an error.
